# Generated by Django 4.2.7 on 2023-11-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_model_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/profile_avatar'),
        ),
    ]
