# Generated by Django 4.2.7 on 2023-11-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_model_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_model',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='match_model',
            name='refree',
        ),
        migrations.AlterField(
            model_name='user_model',
            name='role',
            field=models.CharField(choices=[('Organizer', 'organizer'), ('Coach', 'Coach'), ('Player', 'player'), ('Other', 'other')], max_length=30),
        ),
    ]
